{% set name = "strsimpy" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0842eb57f7af86c882a59a1bc8721ec2580a267e563fd0503ced2972040372c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python


test:
  imports:
    - strsimpy

about:
  home: https://github.com/luozhouyang/python-string-similarity
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python3.x implementation of tdebatty/java-string-similarity
  description: A library implementing different string similarity and distance measures.
  doc_url: https://github.com/luozhouyang/python-string-similarity
  dev_url: https://github.com/luozhouyang/python-string-similarity

extra:
  recipe-maintainers:
    - aschonfeld
