{% set name = "strsimpy" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a02fd6eb36130311d4978ddbef0248be19a80a715c3100e6ce8d6faab24c8122

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python


test:
  imports:
    - strsimpy

about:
  home: https://github.com/luozhouyang/python-string-similarity
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python3.x implementation of tdebatty/java-string-similarity
  description: A library implementing different string similarity and distance measures.
  doc_url: https://github.com/luozhouyang/python-string-similarity
  dev_url: https://github.com/luozhouyang/python-string-similarity

extra:
  recipe-maintainers:
    - aschonfeld
